name: CI

on: pull_request

jobs:

  build:
    name: Build check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Build check
      run: npm run compile

  test-stable:

    strategy:
      matrix:
        os: [windows-latest, macOS-latest]

    name: Test with VS Code stable on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci && cd test-workspaces && npm ci && cd customized && npm ci
    - name: Test check
      run: npm run ci:stable
      if: matrix.os != 'ubuntu-latest'
    - name: Required for Code display on Linux
      run: sudo apt-get install xvfb
      if: matrix.os == 'ubuntu-latest'
    - name: Test check
      run: xvfb-run --auto-servernum npm run ci:stable
      if: matrix.os == 'ubuntu-latest'
