code --install-extension 1tontech.angular-material
code --install-extension alexiv.vscode-angular2-files
code --install-extension Angular.ng-template
code --install-extension burkeholland.simple-react-snippets
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cyrilletuzi.angular-schematics
code --install-extension DaltonMenezes.aura-theme
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension GraphQL.vscode-graphql
code --install-extension Gruntfuggly.todo-tree
code --install-extension infinity1207.angular2-switcher
code --install-extension john-crowson.angular-file-changer
code --install-extension johnpapa.Angular2
code --install-extension jonkwheeler.styled-components-snippets
code --install-extension loiane.angular-extension-pack
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension obenjiro.arrr
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension rbbit.typescript-hero
code --install-extension rctay.karma-problem-matcher
code --install-extension segerdekort.angular-cli
code --install-extension SimonTest.simontest
code --install-extension steoates.autoimport
code --install-extension stringham.move-ts
code --install-extension styled-components.vscode-styled-components
code --install-extension TabNine.tabnine-vscode
code --install-extension vivaxy.vscode-conventional-commits
code --install-extension WakaTime.vscode-wakatime
code --install-extension wix.vscode-import-cost
code --install-extension zhuangtongfa.material-theme
